version: '3.8'

services:
  chess-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: interesting-chess-scraper
    environment:
      APP_NAME: ${APP_NAME:-interesting-chess}
      VERSION: ${VERSION:-1.0}
      USERNAME: ${USERNAME:-alienoscar}
      EMAIL: ${EMAIL:-garcia.oscar1729@gmail.com}
      IC_OUTPUT_DIR: /app/data
      S3_LOCATION: ${S3_LOCATION:-}
      AWS_REGION: ${AWS_REGION:-us-east-1}
    volumes:
      - ./data:/app/data
    command: >
      --days 7 
      --limit-players 10 
      --verbose
    restart: "no"

  # Optional: monitoring container
  # You could add other services here like:
  # - A file server to serve the JSON output
  # - A monitoring/alerting service
  # - A database to store historical data

volumes:
  chess_data:
    driver: local
